apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  serviceAccountName: cart
  containers:
    - name: test
      image: 667211563329.dkr.ecr.us-east-1.amazonaws.com/schema-loader:2.0.1
#      args: [ "one", "two" ]
      command: [ "tail", "-f", "/dev/null" ]
      args: [ "mongo", "catalogue" ]
      env:
        - name: env
          value: prod


