apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::667211563329:role/ssm-eks



---

apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    component: catalogue
spec:
  serviceAccountName: catalogue
  containers:
    - name: catalogue
      image: 667211563329.dkr.ecr.us-east-1.amazonaws.com/catalogue:2.0.1
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-store
      image: 667211563329.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:2.0.3
      args: ["DOCUMENTDB:prod.catalogue.mongo"]
      volumeMounts:
        - mountPath: /params
          name: params
  volumes:
    - name: params
      emptyDir:
        sizeLimit: 100Mi


---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
